public class GeoTabUser {
    @AuraEnabled public Integer acceptedEULA;    //19
    @AuraEnabled public Integer driveGuideVersion;    //0
    @AuraEnabled public Integer wifiEULA;    //0
    //public cls_activeDashboardReports[] activeDashboardReports;
    //public cls_bookmarks[] bookmarks;
    @AuraEnabled public String activeFrom;    //2022-08-12T17:03:00.293Z
    @AuraEnabled public String activeTo;    //2050-01-01T00:00:00.000Z
    //public cls_availableDashboardReports[] availableDashboardReports;
    //public cls_cannedResponseOptions[] cannedResponseOptions;
    public boolean changePassword;
    @AuraEnabled public String comment;    //
    //public cls_companyGroups[] companyGroups;
    public String dateFormat;    //MM/dd/yy HH:mm:ss
    public String phoneNumber;    //
    public String displayCurrency;    //Cad
    public String countryCode;    //
    public String phoneNumberExtension;    //
    public String defaultGoogleMapStyle;    //Roadmap
    public String defaultMapEngine;    //MapBox
    public String defaultOpenStreetMapStyle;    //MapBox
    public String defaultHereMapStyle;    //Roadmap
    public String defaultPage;    //helpGuide
    public String designation;    //
    public String employeeNo;    //
    @AuraEnabled public String firstName;    //blake
    public String fuelEconomyUnit;    //LitersPer100Km
    public String electricEnergyEconomyUnit;    //LitersEPer100Km
    public String hosRuleSet;    //None
    public boolean isYardMoveEnabled;
    public boolean isPersonalConveyanceEnabled;
    public boolean isExemptHOSEnabled;
    @AuraEnabled public String authorityName;    //Accel Entertainment, Inc
    public String authorityAddress;    //
    @AuraEnabled public String id;    //b20
    public boolean isEULAAccepted;
    public boolean isNewsEnabled;
    public boolean isServiceUpdatesEnabled;
    public boolean isLabsEnabled;
    public boolean isMetric;
    public String language;    //en
    public String firstDayOfWeek;    //Sunday
    public String lastName;    //
    //public cls_mapViews[] mapViews;
    public String name;    //blake@bluearrowmail.com
    //public cls_privateUserGroups[] privateUserGroups;
    //public cls_reportGroups[] reportGroups;
    //public cls_securityGroups[] securityGroups;
    public boolean showClickOnceWarning;
    public String timeZoneId;    //America/New_York
    public String userAuthenticationType;    //MyAdmin
    public String zoneDisplayMode;    //Default
    @AuraEnabled public String companyName;    //Accel Entertainment, Inc
    public String companyAddress;    //
    public String carrierNumber;    //
    @AuraEnabled public String lastAccessDate;    //2022-08-16T12:54:44.518Z
    public boolean isDriver;
    public boolean isEmailReportEnabled;
    public String featurePreview;    //
}